<?php

namespace filmBundle\Repository;

/**
 * acteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class acteurRepository extends \Doctrine\ORM\EntityRepository
{
}
