post_index:
    path:     /
    defaults: { _controller: "blogBundle:Post:index" }
    methods:  [GET, POST]

post_show:
    path:     /{id}/show
    defaults: { _controller: "blogBundle:Post:show" }
    methods:  GET
post_shows:
    path:     /{id}/shows
    defaults: { _controller: "blogBundle:Post:shows" }
    methods:  GET

post_new:
    path:     /new
    defaults: { _controller: "blogBundle:Post:new" }
    methods:  [GET, POST]

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "blogBundle:Post:edit" }
    methods:  [GET, POST]

post_delete:
                  path:     /{id}/delete
                  defaults: { _controller: "blogBundle:Post:delete" }
                  methods:  DELETE

post_recherche:
    path:     /recherche
    defaults: { _controller: "blogBundle:Post:recherche" }

post_export:
    path:     /export
    defaults: { _controller: "blogBundle:Post:export" }
